### ISSUE TITLE
Q: difference between https://github.com/mjbvz/vscode-lit-html ?

### ISSUE THREAD

**Issue by kkimdev** [runem/vscode-lit-plugin#11]
Hi, since there is another very similar plugin, https://github.com/mjbvz/vscode-lit-html , it would be great to have a section explaining the difference and the motivation behind developing this new plugin.  Thanks!

**Comment by runem** [comment]
Thanks for the suggestion! I'll add a section to the readme comparing this plugin to [vscode-lit-html](https://github.com/mjbvz/vscode-lit-html) very soon. Here's a draft of what it would look like.

| Feature                 | [vscode-lit-html](https://github.com/mjbvz/vscode-lit-html)   | [vscode-lit-plugin](https://github.com/runem/vscode-lit-plugin) |
|-------------------------|------------|------------|
| Goto definition         | ❌         | ✅         |
| CSS support             | ❌         | ✅         |
| Check missing imports   | ❌         | ✅         |
| Auto discover web components | ❌    | ✅         |
| Template type checking  | ❌         | ✅         |
| Report unknown attrs    | ❌         | ✅         |
| Report unknown tag names | ❌         | ✅         |
| Quick info              | ✅         | ✅         |
| Auto close tags         | ✅         | ✅         |
| Syntax Highlighting     | ✅         | ✅         |
| Completions             | ✅         | ✅         |
| Formatting              | ✅         | ⚠️ (disabled until problem with nested templates is fixed) |
| Event checking support  | ❌         | ⚠️ (coming soon) |
| Slot checking support   | ❌         | ⚠️ (coming soon) |
| Code folding            | ✅         | ❌         |

**Comment by kkimdev** [comment]
This is quite an improvement!

**Comment by runem** [comment]
The comparison table is now in the readme so therefore I'm closing this issue now 🎉
