### ISSUE TITLE
Type 'TemplateResult' is not assignable to 'TemplateResult'

### ISSUE THREAD

**Issue by LouisStAmour** [runem/vscode-lit-plugin#16]
Seeing `Type 'TemplateResult' is not assignable to 'TemplateResult'` in my list of errors when trying to set a property using the `html` template tag. (Note that the line assigning html`` to TemplateResult doesn't flag any TS errors... just the last line when trying to create a custom element with a TemplateResult-type attribute.)

```ts
import {
  TemplateResult
} from "lit-element";
/* ... */
  @property({ type: TemplateResult }) HtmlValue: TemplateResult = html``;
/* ... */
.HtmlValue=${html``}
```

**Comment by runem** [comment]
Hi Louis, thanks for your issue!

I encountered this issue some time ago, and I fixed it, but I just yet haven't uploaded the new version to the vscode marketplace yet.

I'm in the process of making a CLI that can analyze your lit templates. This CLI uses uses the same internals as this plugin and has all the bug fixes/improvements that will soon come to vscode-lit-plugin. Therefore I'm very curious if you still experience the problem when analyzing your file with this CLI. You can try it out like this: 

```bash
npx lit-analyzer path-to-file-with-problem.ts
```
or
```bash
npx lit-analyzer src
```

If you still experience the problem when using the CLI it would be very useful to know the following:
  1. Is one of the "TemplateResult" class imported from "lit-html" and the other from "lit-element"?
  2. Do you experience the problem always or does it appear under certain circumstances? Eg. if it disappears when you reload the vscode window.

**Comment by LouisStAmour** [comment]
I’ll try the CLI, sure. Earlier it happened regardless of which package or
file I imported, direct or top level. I also validated it happened in the
same file as the component definition, with the same imported copy, if I
recall correctly.

I’d like to say it happened consistently, but no, it changed halfway
through to not knowing what component I’d imported and complaining it
didn’t exist.

I’ll try the CLI and maybe see if I can report this and other bugs in more
detail. I’ll also try compiling the extension from source perhaps. Won’t
likely have time to try this until the weekend, though, we’ll see.

**Comment by runem** [comment]
It sounds like the same problems I encountered some time ago. Technically it can be boiled down to [ts-simple-type](https://github.com/runem/ts-simple-type) not yet being able to handle all types comparisons, therefore falling back to type reference comparison which sometimes fails.

I have compiled the extension myself if you want to give it a try and see if it has been fixed. It would help me a lot, thank you! :-) 

You can download it here: https://drive.google.com/file/d/1TVsJWSYS1ZjVBQXE7Smi0rABSCLEioJ3/view?usp=sharing

**Comment by timreichen** [comment]
Any updates on that issue? Is it going to be solved on the next release?

**Comment by mantou132** [comment]
I have a similar problem, https://github.com/mantou132/gem-boilerplate/blob/master/src/elements/nav.ts#L25
<img width="738" alt="Screen Shot 2019-08-06 at 6 35 13 PM" src="https://user-images.githubusercontent.com/3841872/62533326-f525eb00-b878-11e9-828b-1199745081ea.png">

~solved~ IntelliSense not work it after installing v1.1.0.

analyzer result:
```
$ npx lit-analyzer src
npx: installed 140 in 15.367s
Analyzing 7 files...

  ✓ Found 0 problems in 7 files
```

thanks

**Comment by runem** [comment]
The newest version of lit-plugin ([1.1.6](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin)) has now been released. 

I'm really sorry you had to wait for so long, - this update is long overdue! I look very much forward hearing if the problems have been fixed for you :-)

**Comment by mantou132** [comment]
@runem now lit-plugin works perfectly
Thank you
