### ISSUE TITLE
css ::slotted incorrectly showing at-rule error

### ISSUE THREAD

**Issue by jennasalau** [runem/vscode-lit-plugin#17]
the following code

```
::slotted(.foo) { color: blue; }
```

Shows error `at-rule or selector expected lit-plugin(2322)`

This is valid css and should not show this error.

**Comment by runem** [comment]
Hi Jenna, thanks for opening this issue!

It has now been fixed, but it's not live yet. I expect to publish a new version to vscode marketplace this weekend. I will notify you here when the fix is live :-)

**Comment by jennasalau** [comment]
Awesome :)

**Comment by runem** [comment]
The newest version of lit-plugin ([1.1.6](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin)) has now been released. I completely forgot that I promised this fix! I'm really, really sorry you had to wait for this long :-(
