### ISSUE TITLE
Support for custom decorator instead of default one @customElement

### ISSUE THREAD

**Issue by Stradivario** [runem/vscode-lit-plugin#18]
Hello there!! First of all thank you for the perfect plugin ! 

I would like to ask you is there any chance to set default Decorator to be different from @customElement ?

Example:

#### Current behaviour

```typescript
import { customElement, html, css } from '@rxdi/lit-html';

@customElement('inject-tailwind', {
  template: () => html`
    <link
      href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
      rel="stylesheet"
    />
  `
})
export class TailWindComponent extends HTMLElement {}

```

Expected behaviour

```typescript
import { html, css, Component } from '@rxdi/lit-html';

@Component({
  selector: 'inject-tailwind',
  style: css`
  `,
  template: () => html`
    <link
      href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
      rel="stylesheet"
    />
  `
})
export class TailWindComponent extends HTMLElement {}


declare global {
  interface HTMLElementTagNameMap {
    'inject-tailwind': TailWindComponent;
  }
}

```

Instead of declaring it outside the component is there any chance that i can map specific value to decorator since i really want to get rid of this global declaring on every file but i really DO want to use custom decorator how can i accomplish this ?

You can check the repository here:

https://github.com/rxdi/starter-client-lit-html

Regards to all of you!

:)))

**Comment by runem** [comment]
Hey, thanks for opening this issue :-) I'm happy you like the plugin!

First of all, I'm aware of this limitation, and I have been thinking a lot on how to tackle it. Some time ago I actually made [this issue](https://github.com/runem/ts-lit-plugin/issues/11) in order to discuss solutions (I also suggested a potential solution). You are very welcome to write down your thoughts/requirements/concerns if you have any ideas on how it should work.

A solution that works right now is to use the `@customElement` jsdoc tag. However this also has the limitation that you have to repeat the custom element tag name twice:

```js
/**
 * @customElement inject-tailwind
 */
@Component({
  selector: "inject-tailwind",
  ...
})
export class TailWindComponent extends HTMLElement {}
```

**Comment by Stradivario** [comment]
Thank you for the fast answer! I really like people which are responsible of their projects! :)) 

@runem also defining it that way it will not get automatically @properties decorator and we need to define manual properties inside the comment right ? 

Will try to think about solution of the problem and will let you know.

**Comment by Stradivario** [comment]
Lets proceed the discussion inside the first created issue!
Will close this one and will comment there if i have some proposal solution!

Regards!

**Comment by runem** [comment]
No problems, I'm super invested in this plugin :-)

Are you are thinking about the LitElement `@property` decorator? Everything inside the class declaration will get picked up as expected when you use the jsdoc tag `customElement`, so in this example it will find the "color" property/attribute:

```typescript
/**
 * @customElement inject-tailwind
 */
@Component({
  selector: "inject-tailwind",
  ...
})
export class TailWindComponent extends LitElement {
   @property() color: string;
}
```

If you are not thinking about the LitElement `@property` decorator, I think I will need an example.

**Comment by Stradivario** [comment]
> No problems, I'm super invested in this plugin :-)
> 
> Are you are thinking about the LitElement `@property` decorator? Everything inside the class declaration will get picked up as expected when you use the jsdoc tag `customElement`, so in this example it will find the "color" property/attribute:
> 
> ```ts
> /**
>  * @customElement inject-tailwind
>  */
> @Component({
>   selector: "inject-tailwind",
>   ...
> })
> export class TailWindComponent extends LitElement {
>    @property() color: string;
> }
> ```
> 
> If you are not thinking about the LitElement `@property` decorator, I think I will need an example.

Exactly! This is what i was talking about :) Thank you very much for the details !
