### ISSUE TITLE
Add css`` support

### ISSUE THREAD

**Issue by abdonrd** [runem/vscode-lit-plugin#2]
It would be great to have support for css``!

**Comment by runem** [comment]
I'm working on it :-)

The master branch already has CSS support but I haven't published it to vscode yet.
I'm planning on releasing it later this week after some testing.

**Comment by runem** [comment]
I just published version 0.1.0 with css support 🎉

https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin

**Comment by abdonrd** [comment]
Awesome, thanks! Updating...
