### ISSUE TITLE
Add support to the HTML tooltips and highlight

### ISSUE THREAD

**Issue by abdonrd** [runem/vscode-lit-plugin#6]
The tooltip doesn't work.
Also the HTML tags highlight doesn't work when you set the cursor on a tag.

![feb-23-2019 00-18-41](https://user-images.githubusercontent.com/1007051/53276747-c79d1900-3700-11e9-9ef7-1dfd3bcbca63.gif)

**Comment by runem** [comment]
This seems like a regression because it should work and it works fine for me. I would help me a lot to see your "tsserver.log" again after triggering the problem 👍 

Here's what I see:
![4eely-3snnb](https://user-images.githubusercontent.com/5372940/53285638-fba92600-3762-11e9-96a6-1c773c8bdf64.gif)

**Comment by abdonrd** [comment]
Here it is! [tsserver.log](#)

**Comment by runem** [comment]
Thanks a lot! I'll look into it later today :-)

**Comment by runem** [comment]
I was able to reproduce it :tada: I know what's wrong and I'll fix it later this week when I ship an improved custom element parser which is much more resilient (and also takes care of parsing custom elements using `static get observedAttributes` / `static get properties`). In addition I'm working on setting up tests so we won't see these kinds of regressions again :+1: 

While I work on a fix you can fix it locally by inserting `if (node == null) return;` on line 148 of `~/.vscode/extensions/runem.lit-plugin-0.1.1/node_modules/ts-lit-plugin/lib/parsing/parse-components/flavors/lit-element-flavor.js` or reverting to version `0.1.0` of the plugin.

**Comment by runem** [comment]
@abdonrd I had some time to publish a fix. You should be able to upgrade the plugin to version `0.1.2` now. Please tell me if anything isn't working as expected and thanks for reporting the bug! :-)

**Comment by abdonrd** [comment]
Thanks @runem! Now the tooltip works! 🎉 

But the highlight still doesn't work.
Also the collapse option (on the line number) doesn't work. But maybe this is another issue?

**Comment by runem** [comment]
Great! 

I'm not sure if its possible for a plugin to do highlighting and code-collapse but I'll gladly look into it. I think they should be two different issues labeled as feature requests. You are very welcome to open them or else I'll open them later today.

**Comment by abdonrd** [comment]
I understand that yes it should be possible: https://github.com/mjbvz/vscode-lit-html/issues/35

**Comment by runem** [comment]
Thanks for the heads up! I'll look into it when I have time 👍 Right now I'm working on improving the component parser which I'm expecting to be finished within a week :-)

**Comment by runem** [comment]
Related: #9

**Comment by abdonrd** [comment]
Sounds great, thanks @runem!
